---
- name: register nginx repository key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: add nginx default repositories
  apt_repository: repo='deb http://nginx.org/packages/mainline/debian/ {{ debian.version }} nginx' state=present

- name: add nginx default sources repositories
  apt_repository: repo='deb-src http://nginx.org/packages/mainline/debian/ {{ debian.version }} nginx' state=present

- name: install nginx packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - nginx

- name: adjust user
  lineinfile: "dest=/etc/nginx/nginx.conf state=present regexp='^user' line='user  {{ nginx.user }};'"

- name: adjust workers
  lineinfile: "dest=/etc/nginx/nginx.conf state=present regexp='^worker_processes' line='worker_processes  {{ nginx.workers }};'"

- name: set nginx listen as unix scheme
  set_fact:
    nginx_listen: "unix:{{ php.fastcgi_pass }}"
  when: php.fastcgi_pass.find('/') != -1

- name: set nginx listen as ip scheme
  set_fact:
    nginx_listen: "{{ php.fastcgi_pass }}"
  when: php.fastcgi_pass.find('/') > 0

- name: copy nginx default site
  template: src=default.{{ nginx.php_engine }}.j2 dest=/etc/nginx/conf.d/default.conf
  notify: reload nginx

- name: create document root directory if needed
  file: path={{ nginx.document_root }} state=directory mode=0755

- name: copy phpinfo
  template: src=index.php.j2 dest={{ nginx.document_root }}index.php
  notify: reload nginx
