---
- name: install nginx packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - nginx

- name: copy nginx default conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: copy nginx default site
  template: src=default.{{ nginx.php_engine }}.j2 dest=/etc/nginx/sites-available/default
  notify: reload nginx

- name: create document root directory if needed
  file: path={{ nginx.document_root }} state=directory mode=0755

- name: copy phpinfo
  template: src=index.php.j2 dest={{ nginx.document_root }}index.php
  notify: reload nginx